SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
CAR.DAILY_FEE * 30 * (100 - 
    (SELECT DP.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    WHERE DP.CAR_TYPE = CAR.CAR_TYPE
    AND DURATION_TYPE = '30일 이상')) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON CAR.CAR_TYPE = DP.CAR_TYPE
    AND DP.DURATION_TYPE = '30일 이상'
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' 
    AND END_DATE >= '2022-11-01')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC