WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN G ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(G.ID) AS COUNT, 
    G.GENERATION
FROM ECOLI_GEN G
LEFT JOIN ECOLI_DATA CHILD ON G.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;