WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT H.HOUR, COALESCE(D.COUNT, 0) "COUNT"
FROM HOURS H
LEFT JOIN (
    SELECT HOUR(AO.DATETIME) AS HOUR, COUNT(*) 'COUNT'
    FROM ANIMAL_OUTS AO
    GROUP BY HOUR(DATETIME)
) AS D
ON H.HOUR = D.HOUR
ORDER BY H.HOUR ASC