SELECT HG.EMP_NO, HE.EMP_NAME,
CASE
    WHEN AVG(HG.SCORE) >= 96 THEN "S"
    WHEN AVG(HG.SCORE) >= 90 THEN "A"
    WHEN AVG(HG.SCORE) >= 80 THEN "B"
    ELSE "C"
END AS GRADE,
CASE
    WHEN AVG(HG.SCORE) >= 96 THEN HE.SAL * 0.2
    WHEN AVG(HG.SCORE) >= 90 THEN HE.SAL * 0.15
    WHEN AVG(HG.SCORE) >= 80 THEN HE.SAL * 0.1
    ELSE 0
END AS BONUS
FROM HR_GRADE HG
JOIN HR_EMPLOYEES HE
ON HE.EMP_NO = HG.EMP_NO
GROUP BY HG.EMP_NO, HG.YEAR
ORDER BY HE.EMP_NO ASC
