SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
WHERE CAR.CAR_TYPE = '세단'
AND EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    WHERE RH.CAR_ID = CAR.CAR_ID
    AND RH.START_DATE >= '2022-10-01' AND RH.START_DATE < '2022-11-01'
)
ORDER BY CAR_ID DESC