SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR
WHERE CAR.CAR_TYPE = '세단'
AND EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    WHERE RH.CAR_ID = CAR.CAR_ID
    AND MONTH(RH.START_DATE) = 10
)
ORDER BY CAR_ID DESC